name: 'Validate Json.'
description: 'Validate a json against a schema'
inputs:
  schema:
    description: 'The JSON schema definition file.'
    required: true
  config:
    description: 'The JSON configuration file.'
    required: true
  github_token:
    description: 'Github token to create / update pull-request comments.'
    required: false
  pull_request_comment:
    description: 'Feature flag to create a pull-request comment.'
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'