name: 'Validate Json.'
description: 'Validate a json against a schema'
inputs:
  schema:
    description: 'Schema file'
    required: true
  config:
    description: 'Config file'
    required: true
  github_token:
    description: 'Github token to create / update pull-request comments.'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'