---
name: package

on:
  push:
    branches:
      - main

jobs:
  check:
    name: Package distribution file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Guess next version number
        id: version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
      - name: Package
        run: |
          npm i
          npm run build
          npm test
      - name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git add dist/
          git commit -m "(chore) updating dist" || echo "No changes to commit"
          git push origin HEAD:main
      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create \
            --title "${{ steps.version.outputs.new_tag }}" \
            "${{ steps.version.outputs.new_tag }}" \
            --generate-notes
      - name: Update floating major version tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          export MAJOR_VERSION=$(echo "${{ steps.version.outputs.new_tag }}" | sed 's/\(v[0-9]*\).*/\1/g')
          git tag -d $MAJOR_VERSION || true
          git tag $MAJOR_VERSION
          git push origin $MAJOR_VERSION --force